# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from allotrope.rpc import allotrope_pb2 as allotrope__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in allotrope_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActuationStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dispatch = channel.unary_unary(
                '/allotrope.Actuation/Dispatch',
                request_serializer=allotrope__pb2.DispatchRequest.SerializeToString,
                response_deserializer=allotrope__pb2.DispatchResponse.FromString,
                _registered_method=True)
        self.Observe = channel.unary_unary(
                '/allotrope.Actuation/Observe',
                request_serializer=allotrope__pb2.ObserveRequest.SerializeToString,
                response_deserializer=allotrope__pb2.Observation.FromString,
                _registered_method=True)


class ActuationServicer:
    """Missing associated documentation comment in .proto file."""

    def Dispatch(self, request, context):
        """One dispatch cycle: send a command, receive the telemetry it produced.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """The plant's condition before a command is chosen, for a controller that
        wants a fresh reading rather than trusting the last response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActuationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Dispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.Dispatch,
                    request_deserializer=allotrope__pb2.DispatchRequest.FromString,
                    response_serializer=allotrope__pb2.DispatchResponse.SerializeToString,
            ),
            'Observe': grpc.unary_unary_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=allotrope__pb2.ObserveRequest.FromString,
                    response_serializer=allotrope__pb2.Observation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'allotrope.Actuation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('allotrope.Actuation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Actuation:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Dispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/allotrope.Actuation/Dispatch',
            allotrope__pb2.DispatchRequest.SerializeToString,
            allotrope__pb2.DispatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/allotrope.Actuation/Observe',
            allotrope__pb2.ObserveRequest.SerializeToString,
            allotrope__pb2.Observation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
