# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import allotrope_pb2 as allotrope__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in allotrope_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPlaneStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/allotrope.controlplane.ControlPlane/GetState',
                request_serializer=allotrope__pb2.StateRequest.SerializeToString,
                response_deserializer=allotrope__pb2.StationState.FromString,
                _registered_method=True)
        self.StreamState = channel.unary_stream(
                '/allotrope.controlplane.ControlPlane/StreamState',
                request_serializer=allotrope__pb2.StateRequest.SerializeToString,
                response_deserializer=allotrope__pb2.StationState.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/allotrope.controlplane.ControlPlane/Heartbeat',
                request_serializer=allotrope__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=allotrope__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class ControlPlaneServicer:
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """One state snapshot. Returns NOT_FOUND for an unknown station_id --
        never a default/placeholder StationState.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request, context):
        """Server-streaming: one StationState per `interval_s` (a fixed 1 Hz push
        in the current server, see server.py) until the client disconnects.
        Reconnecting is just calling this again -- there is no session state to
        resume, since sequence_number always restarts from the state at call
        time, not from zero, so a reconnecting client can detect a gap by
        comparing sequence numbers itself.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Liveness and version, independent of any station. What a control-plane
        client should poll to detect "the controller process itself is gone"
        before it ever gets to asking about a specific station.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=allotrope__pb2.StateRequest.FromString,
                    response_serializer=allotrope__pb2.StationState.SerializeToString,
            ),
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=allotrope__pb2.StateRequest.FromString,
                    response_serializer=allotrope__pb2.StationState.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=allotrope__pb2.HeartbeatRequest.FromString,
                    response_serializer=allotrope__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'allotrope.controlplane.ControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('allotrope.controlplane.ControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlane:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/allotrope.controlplane.ControlPlane/GetState',
            allotrope__pb2.StateRequest.SerializeToString,
            allotrope__pb2.StationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/allotrope.controlplane.ControlPlane/StreamState',
            allotrope__pb2.StateRequest.SerializeToString,
            allotrope__pb2.StationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/allotrope.controlplane.ControlPlane/Heartbeat',
            allotrope__pb2.HeartbeatRequest.SerializeToString,
            allotrope__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
